#! /bin/sh
#
case "$1" in
  rebuild)
	echo "Rebuilding po files" >&2
  	i18ndude rebuild-pot --pot locales/plonede.content.pot --create plonede.content .
	;;
  sync)
	echo "Syncing po files" >&2
	i18ndude sync --pot locales/plonede.content.pot locales/*/LC_MESSAGES/plonede.content.po
	;;
  *)
	echo "Usage: $0 rebuild|sync" >&2
	exit 3
	;;
esac
